services:
  seller-frontend:
    build: seller-frontend
    ports:
      - "8000:5000" # the internal docker port is 5000 but we expose to 8000
    depends_on:
      - products-db-rpc
  buyer-frontend:
    build: buyer-frontend
    ports:
      - "8001:5000" # the internal docker port is 5000 but we expose to 8001
    depends_on:
      - customers-db-rpc
      - products-db-rpc

  products-db-rpc:
    build: products-database
    depends_on:
      products-database:
        condition: service_healthy

  customers-db-rpc:
    build: customers-database
    depends_on:
      customers-database:
        condition: service_healthy
  customers-database:
    # to connect to the customers database we use customers-database:5432
    image: postgres:18
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: customers
    volumes:
      - ./data/customers:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d customers" ]
      interval: 5s
      timeout: 5s
      retries: 5

  products-database:
    # to connect to the products database we use products-database:5432
    image: postgres:18
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: products
    volumes:
      - ./data/products:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d products" ]
      interval: 5s
      timeout: 5s
      retries: 5
